language: php

php:
    - '7.2'
    - '7.3'
    - '7.4'

env:
    - COMPOSER_LOWEST=0
    - COMPOSER_LOWEST=1

install:
    - '[ $COMPOSER_LOWEST == 1 ] && composer update --prefer-lowest || composer install'

script:
    - ./bin/phpcs Classes Tests
    - ./bin/phpstan analyze --level 7 Classes
    - ./bin/phpunit
